### ISSUE TITLE
Support prefix

### ISSUE THREAD

**Issue by nuwang** [yandex-cloud/k8s-csi-s3#12]
We were hoping to use an existing bucket with geesefs, with a large amount of data living under an existing prefix. It looks like the csi now only supports dynamically provisioned prefixes. Would it be possible to add back `usePrefix` and `prefix` support? I'd be happy to try and make a PR for it.

**Comment by nuwang** [comment]
@vitalif That's good to hear. Does it also handle the case where it won't try to create or delete the pvc prefix if a custom prefix is defined? I didn't notice a case for it and had to add it in: https://github.com/yandex-cloud/k8s-csi-s3/pull/13/files#diff-80793083e0532aa32cf03aecc5ee3efefced14c5b0d7af3ca7cfc0b03e2b9af8R146

The default behavior on delete seems to be to remove the entire bucket if the prefix is empty, or remove the prefix?

**Comment by vitalif** [comment]
It shouldn't delete anything when you delete the volume if you use static provisioning regardless of prefix setting :-)

**Comment by vitalif** [comment]
I'll close the issue by now, feel free to reopen if you have other questions

**Comment by nuwang** [comment]
I haven't had a chance to test this with a statically provisioned PV yet. I'll report back if there are any issues.

**Comment by nuwang** [comment]
@vitalif A statically provisioned PV works as expected, thanks!
