### ISSUE TITLE
error syncing claim "bd1cb869-b9d5-4e11-94b3-88491da78050": failed to provision volume with StorageClass "csi-s3": rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by fupengzhou** [yandex-cloud/k8s-csi-s3#143]
I1016 03:22:56.546304       1 controller.go:1109] Temporary error received, adding PVC bd1cb869-b9d5-4e11-94b3-88491da78050 to claims in progress
W1016 03:22:56.546337       1 controller.go:961] Retrying syncing claim "bd1cb869-b9d5-4e11-94b3-88491da78050", failure 16
E1016 03:22:56.546363       1 controller.go:984] error syncing claim "bd1cb869-b9d5-4e11-94b3-88491da78050": failed to provision volume with StorageClass "csi-s3": rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by fupengzhou** [comment]
Minio parameter configuration error  in csi-s3-secret

**Comment by fupengzhou** [comment]
Minio parameter configuration error  in csi-s3-secret

**Comment by hinricht** [comment]
@fupengzhou  What was the issue ? I'm getting the same error.
