### ISSUE TITLE
pod keeps pending

### ISSUE THREAD

**Issue by weiwuduzui** [yandex-cloud/k8s-csi-s3#17]
k8s version: 1.22.0
runtime: containerd
os version: centos 7.4
k8s-csi-s3 version: 0.30.9

hi The problem I encountered is that when I create a pod, I can successfully create a pvc in minio, but the pod is always in the pending state. Check the logs of csi-s3 as follows:

I0615 16:32:03.752720       1 main.go:110] Version: v1.2.0-0-g6ef000ae
I0615 16:32:03.752795       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0615 16:32:03.752828       1 connection.go:151] Connecting to unix:///csi/csi.sock
I0615 16:32:05.797278       1 main.go:127] Calling CSI driver to discover driver name
I0615 16:32:05.798941       1 main.go:137] CSI driver name: "ru.yandex.s3.csi"
I0615 16:32:05.799050       1 node_register.go:58] Starting Registration Server at: /registration/ru.yandex.s3.csi-reg.sock
I0615 16:32:05.799233       1 node_register.go:67] Registration Server started at: /registration/ru.yandex.s3.csi-reg.sock
I0615 16:32:07.265819       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0615 16:32:07.344763       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}

**Comment by vitalif** [comment]
Hi, check the pod with `kubectl describe pod ...` - what does it say? Pending pod typically means that it can't be scheduled, so it's probably not related to the CSI.

**Comment by weiwuduzui** [comment]
hi, kubectl describe pod   
The result is as follows：
Warning  FailedMount  25m    kubelet            Unable to attach or mount volumes: unmounted volumes=[webroot], unattached volumes=[webroot kube-api-access-r59p4]: timed out waiting for the condition

**Comment by vitalif** [comment]
Looks strange - mount attempt should be in the log of csi-s3 container. Maybe your k8s host can't reach the S3 server and mount attempt times out?
You can also try to recreate the volume with `--debug_s3` and look for added debug messages.

**Comment by weiwuduzui** [comment]
k8s can be connected to minio normally, and the corresponding pvc has been created on minio, but the pod has been pending, but I can use this majst01/csi-driver-s3 on github and it can be used normally

Use geesefs to operate minio normally, as follows:

root@master01:/# geesefs --endpoint http://192.168.96.120:9000 zadig /mnt
root@master01:/# cd /mnt/
root@master01:/mnt# ls
root@master01:/mnt# echo aa > a.txt

minio：
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/19463101/174304590-226aa5a3-538e-49ea-80f4-2a7d3f2f1dae.png">

**Comment by vitalif** [comment]
Is geesefs process is present (ps ax|grep geesefs) when the pod is being started (i.e. in your case while it is pending)?
Also check `kubectl get pvc`, is it Bound?

**Comment by weiwuduzui** [comment]
pvc is bound

pod of csi-s3:

root@node01:/# ps -ef
UID PID PPID C STIME TTY TIME CMD
root 1 0 0 02:19 ? 00:00:01 /s3driver --endpoint=unix:///csi/csi.sock --nodeid=node01 --v=4
root 12 0 0 14:35 pts/0 00:00:00 sh -c clear; (bash || ash || sh)
root 20 12 0 14:35 pts/0 00:00:00 sh -c clear; (bash || ash || sh)
root 21 20 0 14:35 pts/0 00:00:00 bash
root 345 21 0 14:37 pts/0 00:00:00 ps -ef
root@node01:/# ps -ef|grep gee
root 347 21 0 14:37 pts/0 00:00:00 grep gee

**Comment by vitalif** [comment]
Ok... check all other system containers ) like csi-attacher and so on. Look for errors in logs.)
It seems the request doesn't reach csi-s3 if geesefs process is absent.

**Comment by weiwuduzui** [comment]
csi-attacher pod:

k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource

**Comment by vitalif** [comment]
Ok so it's version related and it's the same bug as #6. Ok, I'll update resource definitions. For now you can replace v1beta1 for those resources by hand

**Comment by vitalif** [comment]
Fixed in 0.31.3.
