### ISSUE TITLE
csi-s3-driver image 0.31.3 does not exist

### ISSUE THREAD

**Issue by nuwang** [yandex-cloud/k8s-csi-s3#19]
The driver image specified here: https://github.com/yandex-cloud/k8s-csi-s3/blob/ec05cec2525255cadd9ad2a72774ca582e6b8a30/deploy/helm/values.yaml#L10

does not exist.

**Comment by vitalif** [comment]
Sorry, added it + I finally fixed "make push" which was always missing to push that tag from CI :)
