### ISSUE TITLE
The link to built docker images in manifests are not publicly available or invalid

### ISSUE THREAD

**Issue by tranx** [yandex-cloud/k8s-csi-s3#2]
Issue: I am trying to evaluate this operator on k8s. However, I can't seem to be able to pull the image.
When proceeding with CLI :

$ docker pull cr.yandex/crp9ftr22d26age3hulg/yandex-csi-s3:0.30.4

Error response from daemon: repository cr.yandex/crp9ftr22d26age3hulg/yandex-csi-s3 not found: name unknown: Repository crp9ftr22d26age3hulg/yandex-csi-s3 not found ; requestId = a66d8c9a-a81d-4d4d-9350-1f6e8723d831

I imagine that there may currently be some restrictions on who can pull the images. As the project now seems public, it would be nice to have some publicly accessible images for these containers.

**Comment by vitalif** [comment]
Where did you take this link from?
Manifests in the repo have cr.yandex/crp9ftr22d26age3hulg/csi-s3:0.30.4

**Comment by tranx** [comment]
Thanks for the swift reply and for spotting the error.

Indeed, the issue is on my side.  I had to do many find/replaces,
as I have also have `ctrox csi-s3` csi running on the cluster, and
I wanted to be sure not to break the already existing operator.

As much as  I recognize my error here. I would try to recommend that using
different(from ctrox) names
for the operators in k8s deploy as it would allow easier testing for users
that already have an operator installed.
Now, this is not critical, as I imagine that the helm chart will simplify
this too.

Thanks again.
