### ISSUE TITLE
Provide mounting for a specific folder in bucket

### ISSUE THREAD

**Issue by core3750x** [yandex-cloud/k8s-csi-s3#21]
s3fs supports mounting specific folder inside a bucket. For example you can mount it by this way: _bucket_name:/folder_.
Does geesefs support this functionality? If not may it be implemented?
When i define existing bucket in storageClass manifest like mentioned above way i can see error logs in pvc describe` Bucket name contains invalid characters`

**Comment by aixiamomo** [comment]
I had the same problem when use PersistentVolumeClaim.(not pvc_manual)

**Comment by vitalif** [comment]
Hi, of course it's implemented long ago, it's even in examples https://github.com/yandex-cloud/k8s-csi-s3/blob/master/deploy/kubernetes/examples/pvc-manual.yaml#L33
GeeseFS also supports it, see `geesefs -h`:
`   geesefs [global options] bucket[:prefix] mountpoint`
