### ISSUE TITLE
Is it correct to use emptyDir for socket-path in provisioner.yaml ?

### ISSUE THREAD

**Issue by akosyrev** [yandex-cloud/k8s-csi-s3#22]
Hi.
I just noticed that in [provisioner.yaml ](https://github.com/yandex-cloud/k8s-csi-s3/blob/master/deploy/kubernetes/provisioner.yaml#L102-L107) you use emptyDir inside pod with path /var/lib/kubelet/plugins/ru.yandex.s3.csi/ where (i guess) should be located csi.sock. 

And in [attacher.yaml](https://github.com/yandex-cloud/k8s-csi-s3/blob/master/deploy/kubernetes/attacher.yaml#L92-L99) you are using hostPath.

Actually, I've installed this csi-s3 plugin couple weeks ago, created pods with pv(c) using s3 and everything was fine. Today something happens and my k8s couldnot detach and reattach pv for a recreated pod (created from sts if it's matter).
Logs of csi-attacher-s3-0 are filled with a lot of 

> W0705 15:40:59.256683       1 connection.go:173] Still connecting to unix:///var/lib/kubelet/plugins/ru.yandex.s3.csi/csi.sock

I've checked **/var/lib/kubelet/plugins/ru.yandex.s3.csi/** on master-node, where **csi-provisioner-s3-0** and **csi-attacher-s3-0** are running, and there is no csi.sock

Upd: I also checked path  **/var/lib/kubelet/plugins/ru.yandex.s3.csi/** in **csi-provisioner-s3-0** pod and csi.sock exists there. Same path inside **csi-attacher-s3-0** pod is empty

**Comment by kashapovd** [comment]
Hi! I recently saw the same problem and commented one of the issue here https://github.com/yandex-cloud/k8s-csi-s3/issues/9#issuecomment-1173890315

**Comment by vitalif** [comment]
Attacher is obsolete and it's now removed, so the bug is not relevant anymore
