### ISSUE TITLE
[Feature request] Allow to create a pvc with a RO bucket

### ISSUE THREAD

**Issue by tcassaert** [yandex-cloud/k8s-csi-s3#38]
We have a read-only S3 bucket, provided by a cloud provider. We would like to be able to mount this bucket in pods. 

Currently, the docs state:
```
If the bucket is specified, it will still be created if it does not exist on the backend. Every volume will get its own prefix within the bucket which matches the volume ID. When deleting a volume, also just the prefix will be deleted.
```
This means that the `csi-provisioner` tries to create a directory in the already existing bucket. This is problematic for us, as the bucket we would like to use, is read-only and thus we get an `Access denied` when trying to create the `pvc`.

An option to use the existing bucket as-is, without creating a subdirectory by default would solve this issue.

**Comment by vitalif** [comment]
Hi, this option is actually available, it's just not described in the README:
https://github.com/yandex-cloud/k8s-csi-s3/blob/master/deploy/kubernetes/examples/pvc-manual.yaml
By using a statically provisioned PV you can mount a pre-existing bucket and prefix.

**Comment by vitalif** [comment]
Added a note to README: https://github.com/yandex-cloud/k8s-csi-s3/#static-provisioning

**Comment by tcassaert** [comment]
That works indeed! Thanks!
