### ISSUE TITLE
Expose chart via GitHub pages

### ISSUE THREAD

**Issue by andrewroffey** [yandex-cloud/k8s-csi-s3#39]
It would be handy for the csi-s3 package to be exposed in a repository using GitHub pages.

Ref:
https://helm.sh/docs/topics/chart_repository/
https://helm.sh/docs/howto/chart_releaser_action/

**Comment by Kashemir001** [comment]
If you want to grab the chart from a remote repository, a currently working workaround could be:
`helm pull oci://cr.yandex/crp9ftr22d26age3hulg/yandex-cloud/csi-s3/csi-s3` ,
or use that URL with any other Helm command.

That URL is taken from:
https://github.com/yandex-cloud/k8s-csi-s3/blob/519c4f0bd7f661bd09cc2f4b20b460c2eb26cd77/deploy/helm/manifest.yaml#L2

**Comment by stevefan1999-personal** [comment]
The charts repo can be accessed at https://yandex-cloud.github.io/k8s-csi-s3

**Comment by vitalif** [comment]
Totally correct :-) added it to README.
