### ISSUE TITLE
issue when mounting  Static Provisioning PV to multi pods

### ISSUE THREAD

**Issue by shakegod** [yandex-cloud/k8s-csi-s3#43]
created two static provisioning PV with same prefix and same s3 bucket(mybucket/myprefix) and mounted to two pods: Only one pod can access s3 and the other no will lose the connection.

and tried "add --no-systemd to parameters.options", didn't work 

So what I do to allow multi pods to access the same prefix? Thanks.

**Comment by vitalif** [comment]
Hi! Good point. Systemd service names for two mounts probably collide. For now you should try to add --no-systemd to parameters.options of the PV (not storage class) - it works in that case, but each mount starts its own copy of geesefs which isn't too good probably. I'll look into this issue.

**Comment by vitalif** [comment]
Fixed in the latest release, please try 0.34.7
