### ISSUE TITLE
csi-s3-test-nginx AttachVolume.Attach failed for volume

### ISSUE THREAD

**Issue by xuzhe521** [yandex-cloud/k8s-csi-s3#53]
Kubernetes v1.23.0
![image](https://github.com/yandex-cloud/k8s-csi-s3/assets/35841999/fafd0ed3-ffbc-43a8-9536-cd8b77e0ff32)
csi-provisioner log
`I0517 20:09:35.241760       1 controller.go:1335] provision "default/csi-s3-pvc" class "csi-s3": started
I0517 20:09:35.241983       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-s3-pvc", UID:"1083ef7e-3d80-4708-81df-cdfefea6d9fc", APIVersion:"v1", ResourceVersion:"56383159", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/csi-s3-pvc"
I0517 20:09:35.252140       1 controller.go:762] create volume rep: {CapacityBytes:5368709120 VolumeId:pvc-1083ef7e-3d80-4708-81df-cdfefea6d9fc VolumeContext:map[capacity:5368709120 mounter:geesefs options:--memory-limit 1000 --dir-mode 0777 --file-mode 0666] ContentSource:<nil> AccessibleTopology:[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0517 20:09:35.252216       1 controller.go:838] successfully created PV pvc-1083ef7e-3d80-4708-81df-cdfefea6d9fc for PVC csi-s3-pvc and csi volume name pvc-1083ef7e-3d80-4708-81df-cdfefea6d9fc
I0517 20:09:35.252246       1 controller.go:1442] provision "default/csi-s3-pvc" class "csi-s3": volume "pvc-1083ef7e-3d80-4708-81df-cdfefea6d9fc" provisioned
I0517 20:09:35.252289       1 controller.go:1459] provision "default/csi-s3-pvc" class "csi-s3": succeeded
I0517 20:09:35.257532       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-s3-pvc", UID:"1083ef7e-3d80-4708-81df-cdfefea6d9fc", APIVersion:"v1", ResourceVersion:"56383159", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-1083ef7e-3d80-4708-81df-cdfefea6d9fc
I0517 20:12:31.275352       1 reflector.go:530] sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:872: Watch close - *v1.PersistentVolume total 9 items received
I0517 20:12:35.269276       1 reflector.go:530] sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:875: Watch close - *v1.StorageClass total 0 items received
I0517 20:13:43.177116       1 reflector.go:530] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.PersistentVolumeClaim total 11 items received
I0517 20:15:06.175241       1 reflector.go:530] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.StorageClass total 0 items received
I0517 20:17:54.277344       1 reflector.go:530] sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:875: Watch close - *v1.StorageClass total 0 items received
I0517 20:19:29.205444       1 reflector.go:530] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.PersistentVolumeClaim total 0 items received
I0517 20:20:24.175715       1 reflector.go:381] k8s.io/client-go/informers/factory.go:134: forcing resync
I0517 20:20:24.273645       1 reflector.go:381] sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:872: forcing resync
I0517 20:20:35.191250       1 reflector.go:530] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.StorageClass total 3 items received
I0517 20:20:57.280450       1 reflector.go:530] sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:872: Watch close - *v1.PersistentVolume total 0 items received
I0517 20:24:24.282455       1 reflector.go:530] sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:875: Watch close - *v1.StorageClass total 6 items received`
csi-s3 log
- I0517 20:06:11.488371       1 geesefs.go:142] Starting geesefs using systemd: /var/lib/kubelet/plugins/ru.yandex.s3.csi/geesefs -f -o allow_other --endpoint http://10.244.1.42:9000/minio --setuid 65534 --setgid 65534 --memory-limit 1000 --dir-mode 0777 --file-mode 0666 pvc-1d0004dd-6763-4cc6-9abb-5b32e74e7b2c: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1d0004dd-6763-4cc6-9abb-5b32e74e7b2c/globalmount
E0517 20:06:23.033948       1 utils.go:101] GRPC error: Timeout waiting for mount
I0517 20:07:27.124221       1 utils.go:97] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0517 20:07:27.130493       1 utils.go:97] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0517 20:07:27.131927       1 utils.go:97] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0517 20:07:27.132819       1 utils.go:97] GRPC call: /csi.v1.Node/NodeStageVolume
I0517 20:07:27.138459       1 geesefs.go:142] Starting geesefs using systemd: /var/lib/kubelet/plugins/ru.yandex.s3.csi/geesefs -f -o allow_other --endpoint http://10.244.1.42:9000/minio --setuid 65534 --setgid 65534 --memory-limit 1000 --dir-mode 0777 --file-mode 0666 pvc-1d0004dd-6763-4cc6-9abb-5b32e74e7b2c: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1d0004dd-6763-4cc6-9abb-5b32e74e7b2c/globalmount
E0517 20:07:38.696702       1 utils.go:101] GRPC error: Timeout waiting for mount
I0517 20:09:40.715093       1 utils.go:97] GRPC call: /csi.v1.Node/NodeGetCapabilities

**Comment by vitalif** [comment]
Hi, please check the system log (journalctl) on the host when mounting. GeeseFS writes its error messages there.

**Comment by vitalif** [comment]
Or maybe it was related to #62 if you installed it using Helm

**Comment by nickmi** [comment]
Hello i have the same issue, any solutions ?

**Comment by vitalif** [comment]
You should first diagnose it, maybe you have kubelet path mismatch or something like that.
CSI driver starts geesefs on host, it should start and mount the directory inside a directory bound into the csi container.
"Timeout waiting for mount" means that either 1) geesefs failed to start, or 2) it started but in a wrong path for example if you have different kubelet path.
So you should try to start it, check that geesefs is running on the host, check the mount path and check that it's available in the csi container. Something like that. Geesefs writes logs to syslog on the host, so look there.

**Comment by nickmi** [comment]
> You should first diagnose it, maybe you have kubelet path mismatch or something like that. CSI driver starts geesefs on host, it should start and mount the directory inside a directory bound into the csi container. "Timeout waiting for mount" means that either 1) geesefs failed to start, or 2) it started but in a wrong path for example if you have different kubelet path. So you should try to start it, check that geesefs is running on the host, check the mount path and check that it's available in the csi container. Something like that. Geesefs writes logs to syslog on the host, so look there.

Apparently its a DNS issue. It cannot resolve the name where the minio service resides inside the cluster. Changing the service to NodePort and hardcoding the ip works. Interestingly the pvc.yaml works fine with either configuration.

![image](https://github.com/yandex-cloud/k8s-csi-s3/assets/2481323/98cbf2ed-e7a1-4044-b267-9e942c99a493)

**Comment by ZYWNB666** [comment]
> > You should first diagnose it, maybe you have kubelet path mismatch or something like that. CSI driver starts geesefs on host, it should start and mount the directory inside a directory bound into the csi container. "Timeout waiting for mount" means that either 1) geesefs failed to start, or 2) it started but in a wrong path for example if you have different kubelet path. So you should try to start it, check that geesefs is running on the host, check the mount path and check that it's available in the csi container. Something like that. Geesefs writes logs to syslog on the host, so look there.
> 
> Apparently its a DNS issue. It cannot resolve the name where the minio service resides inside the cluster. Changing the service to NodePort and hardcoding the ip works. Interestingly the pvc.yaml works fine with either configuration.
> 
> ![image](https://private-user-images.githubusercontent.com/2481323/259739394-98cbf2ed-e7a1-4044-b267-9e942c99a493.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTU1NjUsIm5iZiI6MTcxOTM5NTI2NSwicGF0aCI6Ii8yNDgxMzIzLzI1OTczOTM5NC05OGNiZjJlZC1lN2ExLTQwNDQtYjI2Ny05ZTk0MmM5OWE0OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjZUMDk0NzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc4NzRkODA2ODMzZWUwNDEyZDY3NDU1MzY1NTRkOWZkMDVjYmQyNDAyOWQ3MGM5ZGQ1NjQwNWVlOTVjMmE5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jl775U1ezx5UPG8sj8H9yU9r8IhqTu8llxBKQUBMHak)

look look https://github.com/ctrox/csi-s3/pull/76/files

**Comment by ZYWNB666** [comment]
我也遇到了这个问题，但是我用的是s3fs，我想指定pv在minio的bucket上的名字，但是没成功，你这个问题解决了吗
