### ISSUE TITLE
Support kubernetes 1.22. storage.k8s.io/v1beta1 not more avialable

### ISSUE THREAD

**Issue by A-SOM** [yandex-cloud/k8s-csi-s3#6]
The storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass, and VolumeAttachment is no longer served as of v1.22.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#storage-resources-v122

E0217 10:12:58.218960       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource
I0217 10:12:59.219153       1 reflector.go:188] Listing and watching *v1beta1.VolumeAttachment from k8s.io/client-go/informers/factory.go:135

**Comment by d0zingcat** [comment]
> The storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass, and VolumeAttachment is no longer served as of v1.22. https://kubernetes.io/docs/reference/using-api/deprecation-guide/#storage-resources-v122
> 
> E0217 10:12:58.218960 1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.VolumeAttachment: the server could not find the requested resource I0217 10:12:59.219153 1 reflector.go:188] Listing and watching *v1beta1.VolumeAttachment from k8s.io/client-go/informers/factory.go:135

You could refer to `attacher.yaml` and upgrade the image version up to v3.0.1 and try again.
