### ISSUE TITLE
Helm chart uses an outdated template file

### ISSUE THREAD

**Issue by Kashemir001** [yandex-cloud/k8s-csi-s3#62]
Hello!

After comparing the output from `helm template` of the project's Helm chart and fixed Kubernetes manifests, it seems that changes brought by commits https://github.com/yandex-cloud/k8s-csi-s3/commit/ecf1031dfc99a09adae5f34da3b1642e24cb3bcc and https://github.com/yandex-cloud/k8s-csi-s3/commit/bfba08742c1ffc831664bae1958ed0c1dad69c83 are not reflected is the [csi-s3.yaml](https://github.com/yandex-cloud/k8s-csi-s3/blame/519c4f0bd7f661bd09cc2f4b20b460c2eb26cd77/deploy/helm/templates/csi-s3.yaml) template file.
If that is not on purpose and was just simply overlooked, I can throw in a PR for that.

By the way, is there any particular reason Helm chart default values use `cr.yandex` repo for container images, and Kubernetes manifests use `quay.io` repo? I suppose those images are just mirrored. Also, for main `csi-s3` image, in both cases `cr.yandex` repo is used, but it still differs a little, which creates minor extra complexity:
https://github.com/yandex-cloud/k8s-csi-s3/blob/519c4f0bd7f661bd09cc2f4b20b460c2eb26cd77/deploy/kubernetes/csi-s3.yaml#L74
vs
https://github.com/yandex-cloud/k8s-csi-s3/blob/519c4f0bd7f661bd09cc2f4b20b460c2eb26cd77/deploy/helm/values.yaml#L10

**Comment by vitalif** [comment]
Hi. Oops, it seems you're right, thanks. I'll fix it.
Image name differs because yandex cloud marketplace required a special format for image names. So I didn't change it, but rather I made CI to push the same image under both names...
