### ISSUE TITLE
I applied pod.yaml file but pod is in container-creating state

### ISSUE THREAD

**Issue by zhaoxin-BF** [yandex-cloud/k8s-csi-s3#80]
I'm testing it, but I got an error，

this is my pod events:
Warning  FailedMount  6s (x15 over 23m)  kubelet            MountVolume.MountDevice failed for volume "pvc-d59daaab-0b40-4491-b56c-69e44f5145e0" : rpc error: code = Unknown desc = Timeout waiting for mount

this is my pvc，it seems all right
<img width="1402" alt="image" src="https://github.com/yandex-cloud/k8s-csi-s3/assets/42676746/b0fbd98b-5e96-4aed-a247-9fb764fd2ddd">

**Comment by Jonathan-Eid** [comment]
what was the issue?
