### ISSUE TITLE
csi-s3(v0.37.4) container crashed, I see many restart counts in k8s

### ISSUE THREAD

**Issue by 2232729885** [yandex-cloud/k8s-csi-s3#82]
<img width="795" alt="微信图片_20231219160739" src="https://github.com/yandex-cloud/k8s-csi-s3/assets/138634190/6ddfaed9-2558-404c-979c-167987dd0fff">
<img width="1016" alt="微信图片_20231219160736" src="https://github.com/yandex-cloud/k8s-csi-s3/assets/138634190/a385af8e-ce98-47e8-adac-854b8df28f72">

uname -r 
3.10.0-1160.99.1.el7.x86_64

logs:
2023-12-19T10:10:21.244262389+08:00 stderr F 
2023-12-19T10:11:26.197174715+08:00 stderr F I1219 02:11:26.191690       1 utils.go:97] GRPC call: /csi.v1.Node/NodeGetCapabilities

i can't see any crashing related logs in container logs

**Comment by vitalif** [comment]
Hi, sorry, I can't tell anything about the crash without logs... which logs did you check? By the way, your kernel is pretty old.

**Comment by 2232729885** [comment]
> Hi, sorry, I can't tell anything about the crash without logs... which logs did you check? By the way, your kernel is pretty old.

has resolved, i checked the /var/log/message, it said that 'Out of memory', so kernel killed the csi-s3 related container process
![image](https://github.com/yandex-cloud/k8s-csi-s3/assets/138634190/2000e0e7-d7b0-4334-89f6-2c93f6104216)

**Comment by vitalif** [comment]
Ok cool
